config/routes.rb
Hld::Application.routes.draw do

  resource :summary, only: [:show]
  resources :disease_maps, only: [:index, :show]
  resources :disease_tables, only: [:index, :show]
  resources :sra, only: [:show]
  resource :welcome, only: [:show]

  root 'summaries#show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  DEATH_STATS_KEYS = %w(all asthma cancer chd copd deaths3450 diabetes est_pop pct3450 rate3450 stroke)

end

app/controllers/disease_maps_controller.rb
class DiseaseMapsController < ApplicationController
  def index
    @death_stats_keys = DEATH_STATS_KEYS
    gon.death_stats_keys = @death_stats_keys
  end

  def show
    @disease_name = params[:id]
    gon.disease_name = @disease_name
  end
end

app/controllers/disease_tables_controller.rb
class DiseaseTablesController < ApplicationController
  def index
    @death_stats_keys = DEATH_STATS_KEYS
    gon.death_stats_keys = @death_stats_keys
  end

  def show
    @disease_name = params[:id]
    gon.disease_name = @disease_name
  end
end

app/controllers/sra_controller.rb
class SraController < ApplicationController
  def show
    gon.sra_id = params[:id]
  end
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disease_maps_helper.rb
module DiseaseMapsHelper
end

app/helpers/disease_tables_helper.rb
module DiseaseTablesHelper
end

app/helpers/sra_helper.rb
module SraHelper
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/disease_maps/index.html.erb
<h1>Disease Maps</h1>
<%- @death_stats_keys.each do |death_stat_name| -%>
  <h2>
    <%= link_to death_stat_name.humanize, disease_map_path(death_stat_name) %>
  </h2>
<%- end -%>

app/views/disease_maps/show.html.erb
<h1><%= @disease_name.humanize %> Map</h1>

<script text="text/javascript">
  var width = 800,
      height = 600;


  var svg = d3.select("body").append("svg")
      .attr("width", width)
      .attr("height", height);

  var projection = d3.geo.mercator()
      .center(['-116.60', '33.12'])
      .scale(25000);

  var path = d3.geo.path()
      .projection(projection);

  var color = d3.scale.quantize()
      .range(["#ffeda0", "#feb24c", "#f03b20"]);

  d3.json("/sra_coords.geojson", function(json) {

    var buckets = 9;
    var colors = ['rgb(255,255,204)','rgb(255,237,160)','rgb(254,217,118)','rgb(254,178,76)','rgb(253,141,60)','rgb(252,78,42)','rgb(227,26,28)','rgb(189,0,38)','rgb(128,0,38)'];

    console.log(d3.values(json));

    var min = 0;
    var max = 650;
    console.log(min, max);
    var colorScale = d3.scale.quantile()
        .domain([min, buckets - 1, max])
        .range(colors);

    svg.selectAll("path")
        .data(json.features)
        .enter()
        .append("path")
        .attr("d", path)
        .style("fill", function(d) {
          var value = d.properties[gon.disease_name];
          if (value) {
            return colorScale(value);
          } else {
            return '#ccc';
          }
        });
//        .on("click", function(e) {
//          console.log('event:',e);
//          alert("E");
//        });
  });
</script>

app/views/disease_tables/index.html.erb
<h1>Available Disease Tables</h1>

<%- @death_stats_keys.each do |death_stat_name| -%>
  <div id="<%= death_stat_name %>">
  <h2>
    <%= link_to death_stat_name.humanize, disease_table_path(death_stat_name) %>
  </h2>
  </div>

  <script text="text/javascript">
    var data_table = new Array();
    var max = -Infinity;
    var min = Infinity;
    for (var i = 0; i < 64; i++) {
      if (death_stats['<%= death_stat_name %>'][i]) {
        var row = death_stats['<%= death_stat_name %>'][i]['by_year'];
        for (var j = 0; j < row.length; j++) {
          if (row[j] > max) { max = row[j]; };
          if (row[j] < min) { min = row[j]; };
        }
        row.unshift(names_by_sra[i]);
        data_table.push(row);
      } else {
      }
    };
    data_table.sort(function(a, b) {
      return b[b.length - 1] - a[a.length - 1];
    });

    var buckets = 9;
    var colors = ['rgb(255,255,204)','rgb(255,237,160)','rgb(254,217,118)','rgb(254,178,76)','rgb(253,141,60)','rgb(252,78,42)','rgb(227,26,28)','rgb(189,0,38)','rgb(128,0,38)'];

    var colorScale = d3.scale.quantile()
        .domain([0, buckets - 1, max])
        .range(colors);

    var body = d3.select("#<%= death_stat_name %>");

    var table = body.append("table");

    var tr = table.selectAll("tr")
        .data(data_table)
        .enter().append("tr");

    var td = tr.selectAll("td")
        .data(function(d, i) {
          return d;
        })
        .enter().append("td")
  //      .text(function(d, i) {
  //        return d;
  //      })
        .style('background-color', function(d){
          return colorScale(d);
        });

  </script>
<%- end -%>

app/views/disease_tables/show.html.erb
<h1><%= @disease_name.humanize %> 2000-2011</h1>

<script text="text/javascript">
  var data_table = new Array();
  var max = -Infinity;
  var min = Infinity;
  for (var i = 0; i < 64; i++) {
    if (death_stats[gon.disease_name][i]) {
      var row = death_stats[gon.disease_name][i]['by_year'];
      for (var j = 0; j < row.length; j++) {
        if (row[j] > max) { max = row[j]; };
        if (row[j] < min) { min = row[j]; };
      }
      row.unshift(names_by_sra[i]);
      data_table.push(row);
    } else {
    }
  };
  data_table.sort(function(a, b) {
    return b[b.length - 1] - a[a.length - 1];
  });

  var buckets = 9;
//  var colors = ["#ffffd9","#edf8b1","#c7e9b4","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#253494","#081d58"]; // alternatively colorbrewer.YlGnBu[9]
  var colors = ['rgb(255,255,204)','rgb(255,237,160)','rgb(254,217,118)','rgb(254,178,76)','rgb(253,141,60)','rgb(252,78,42)','rgb(227,26,28)','rgb(189,0,38)','rgb(128,0,38)'];

  var colorScale = d3.scale.quantile()
      .domain([0, buckets - 1, max])
      .range(colors);

  var body = d3.select("body");

  var table = body.append("table");

  var tr = table.selectAll("tr")
      .data(data_table)
    .enter().append("tr");

  var td = tr.selectAll("td")
      .data(function(d, i) {
        return d;
      })
    .enter().append("td")
      .text(function(d, i) {
        if (typeof(d) == 'string') {
          return d;
        }
      })
      .property("title", function(d) {
        return d;
      })
      .style('background-color', function(d){
        return colorScale(d);
      });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hld" %></title>
    <%= include_gon %>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->


    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">

    <div class="navbar navbar-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">3-4-50 Fact Finder</a>
          <%= image_tag 'civic-knowledge.png', class: 'top-logo' %>
          <%= image_tag 'county-livewell-logos.png', class: 'top-logo' %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Summary Map", summary_path  %></li>
              <li><%= link_to "Disease Maps", disease_maps_path  %></li>
              <li><%= link_to "Disease Tables", disease_tables_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <!--<div class="span3">-->
          <!--<div class="well sidebar-nav">-->
            <!--<ul class="nav nav-list">-->
              <!--<li class="nav-header">Sidebar</li>-->
              <!--<li><%= link_to "Link1", "/path1"  %></li>-->
              <!--<li><%= link_to "Link2", "/path2"  %></li>-->
              <!--<li><%= link_to "Link3", "/path3"  %></li>-->
            <!--</ul>-->
          <!--</div>&lt;!&ndash;/.well &ndash;&gt;-->
        <!--</div>&lt;!&ndash;/span&ndash;&gt;-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>

app/views/sra/show.html.erb
<h1>Sra#show</h1>
<p>Find me in app/views/sra/show.html.erb</p>

app/views/summaries/show.html.erb
<h1>Overall 3-4-50 Rate</h1>
<script text="text/javascript">
  var width = 800,
      height = 600;

  var svg = d3.select("body").append("svg")
      .attr("width", width)
      .attr("height", height);

  var projection = d3.geo.mercator()
      .center(['-116.60', '33.12'])
      .scale(25000);

  var path = d3.geo.path()
      .projection(projection);

  var color = d3.scale.quantize()
      .range(["#ffeda0", "#feb24c", "#f03b20"]);

  d3.json("sra_coords.geojson", function(json) {

    var buckets = 9;
    var colors = ['rgb(255,255,204)','rgb(255,237,160)','rgb(254,217,118)','rgb(254,178,76)','rgb(253,141,60)','rgb(252,78,42)','rgb(227,26,28)','rgb(189,0,38)','rgb(128,0,38)'];

    console.log(d3.values(json));

    var min = 0;
    var max = 650;
    console.log(min, max);
    var colorScale = d3.scale.quantile()
        .domain([min, buckets - 1, max])
        .range(colors);

    svg.selectAll("path")
        .data(json.features)
        .enter()
        .append("path")
        .attr("d", path)
        .style("fill", function(d) {
          var value = d.properties.rate3450;
          if (value) {
            return colorScale(value);
          } else {
            return '#ccc';
          }
        });
  });
</script>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/show.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>